# Database
#server.port = 8091
#spring.datasource.url = jdbc:postgresql://localhost:5432/microservice
#spring.datasource.username = postgres
#spring.datasource.password = 79643414

#Application Configuration == Aquí le indico en que puerto va a correr la aplicación
server:
  port: 8091
## ============================================
## DB
## ============================================
## Aquí está su linea de conexión
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    driverClassName: org.postgresql.Driver
    platform: postgres
    username: postgres
    password: 79643414
#
### ============================================
### JPA / HIBERNATE
### ============================================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    proporties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
  loggin:
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} 5m%n"
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
