server:
  port: 8093
## ============================================
## DB
## ============================================
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/serviceshopping
    driverClassName: org.postgresql.Driver
    platform: postgres
    username: postgres
    password: 79643414
  ### ============================================
  ### JPA / HIBERNATE
  ### ============================================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    proporties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
  loggin:
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} 5m%n"
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
  Feign:
  hystrix:
    enabled: true
  management:
    endpoints:
      web:
        exposure:
          include: "*"
